FROM pypy:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/plots
VOLUME /app/plots

COPY src/ ./src/

ENV PYTHONPATH=/app/src
ENV ACO_CONFIG_PATH=/app/src/Standard/config.json
ENV ACO_PARAMS_PATH=/app/src/Standard/params_config.json
ENV PLOT_DIR_PATH=/app/plots

CMD ["pypy3", "-m", "Standard.main"]